name: flutter_piaui_website
description: The Website developed for community Flutter Piaui.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^6.0.0-alpha.5
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.3.0
  # modular_test: ^2.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
